### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by SayokoHatada** [SayokoHatada/portfolio#9]
■Webアプリの概要
英語学習ツールとして利用いただける絵日記作成アプリです。
日記内容の添削だけではなく、ご自身で入力したキーワードを元にその日記の内容に合う画像をAIで生成し、絵日記として保存することが可能です。

■ProjectsのURL
https://github.com/users/SayokoHatada/projects/2

■MVPリリースまで
- [ ] アプリケーションの立ち上げ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] マイページ
- [ ] 絵日記作成機能
- [ ] AIによる添削機能
- [ ] AIによる画像生成機能
- [ ] 編集/削除機能
- [ ] デプロイ

■MVP後
- [ ] パスワードリセット機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] クイズ機能
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 10月 26日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by SayokoHatada** [comment]
ご確認ありがとうございます。
再度見直し各ストーリーポイントを3以下となる様調整しました。
ご確認のほどよろしくお願いいたします。

**Comment by busitora** [comment]
LGTM！ファイトです！
